services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  db_data:
