---
- name: "Configuration de mon Labo Moussa"
  hosts: localhost
  connection: local
  tasks:
    - name: "Vérifier que le dossier du projet existe"
      stat:
        path: /projets/lab-moussa
      register: folder_check

    - name: "Afficher un message de succès"
      debug:
        msg: "Le dossier /projets/lab-moussa est bien présent !"
      when: folder_check.stat.exists

    - name: "S'assurer que Docker Compose est installé"
      command: docker compose version
      register: docker_check
      changed_when: false

    - name: "S'assurer que le labo Docker est lancé"
      community.docker.docker_compose_v2:
        project_src: /projets/lab-moussa
        state: present
